<a href="https://colab.research.google.com/github/Chdjre/study/blob/master/%E8%AF%BE%E7%A8%8B%E8%AE%BE%E8%AE%A1_%E8%AE%A1%E7%AE%97%E6%9D%83%E9%87%8D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  数据处理

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import os
os.chdir('/content/drive/My Drive/课程设计')

In [ ]:
import pandas as pd
df=pd.read_csv("data for cluster.csv")
df

Unnamed: 0          Id  ...  reply_count  reply_likes_count
0              0   189892290  ...          NaN                NaN
1              1   181008451  ...          NaN                NaN
2              2   141959692  ...          1.0                0.0
3              3  OuTopos531  ...          NaN                NaN
4              4    88143349  ...          NaN                NaN
...          ...         ...  ...          ...                ...
9678        9678   191611318  ...          3.0                1.0
9679        9679   224115455  ...          1.0                0.0
9680        9680   220929267  ...          1.0                1.0
9681        9681   216257139  ...          1.0                3.0
9682        9682   197065724  ...          1.0                0.0

[9683 rows x 10 columns]

各字段含义：
like_count:给出的赞
post_likes_count:发帖被点赞数
post_collections_count：发帖被收藏数
post_repost_count：发帖被转发数
post_count：发帖数
post_reply_count：发帖被回复数
reply_count：回复数
reply_likes_count：回复被点赞数

In [ ]:
dd=pd.read_csv("matrix.csv",names=['post_repost_count','post_reply_count','post_collections_count','post_likes_count'])
dd

post_repost_count  ...  post_likes_count
0           1.000000  ...          1.190769
1           0.866667  ...          1.286154
2           0.907821  ...          1.236923
3           0.839793  ...          1.000000

[4 rows x 4 columns]

In [ ]:
import numpy as np
import numpy.linalg as npla
sum=np.sum(dd,axis=0)
col_arv=dd/sum
w=np.sum(col_arv,axis=1)
w_n=w/np.sum(w)
print("得出的权重为：")
print(w_n)
print("最大特征值为",np.max(npla.eig(dd)[0]))

得出的权重为：
0    0.275981
1    0.266703
2    0.245347
3    0.211969
dtype: float64
最大特征值为 (4.008144100012115+0j)


最大特征值和矩阵的维数4差不多，运用该方法得出的结果合理。

In [ ]:
w_n.tolist()

[0.2759814092600064,
 0.2667027153342267,
 0.24534716247895408,
 0.21196871292681288]

In [ ]:
post_quality=[]
x=np.mat(w_n.tolist())*np.mat(df[['post_repost_count','post_reply_count','post_collections_count','post_likes_count']]).T
df['post_quality']=x.tolist()[0]

In [ ]:
df.drop(['post_repost_count','post_reply_count','post_collections_count','post_likes_count','Unnamed: 0'],axis=1,inplace=True)
df

Id  like_count  ...  reply_likes_count  post_quality
0      189892290         1.0  ...                NaN           NaN
1      181008451        16.0  ...                NaN           NaN
2      141959692         1.0  ...                0.0           NaN
3     OuTopos531         1.0  ...                NaN           NaN
4       88143349         1.0  ...                NaN           NaN
...          ...         ...  ...                ...           ...
9678   191611318         NaN  ...                1.0           NaN
9679   224115455         NaN  ...                0.0           NaN
9680   220929267         NaN  ...                1.0           NaN
9681   216257139         NaN  ...                3.0           NaN
9682   197065724         NaN  ...                0.0           NaN

[9683 rows x 6 columns]

聚类用到的特征
post_count：发帖数
reply_count：回复数
post_quality：发帖质量

In [ ]:
df.drop(['like_count','reply_likes_count'],axis=1,inplace=True)
df

Id  post_count  reply_count  post_quality
0      189892290         NaN          NaN           NaN
1      181008451         NaN          NaN           NaN
2      141959692         NaN          1.0           NaN
3     OuTopos531         NaN          NaN           NaN
4       88143349         NaN          NaN           NaN
...          ...         ...          ...           ...
9678   191611318         NaN          3.0           NaN
9679   224115455         NaN          1.0           NaN
9680   220929267         NaN          1.0           NaN
9681   216257139         NaN          1.0           NaN
9682   197065724         NaN          1.0           NaN

[9683 rows x 4 columns]

In [ ]:
df.fillna(0,inplace=True)
df

Id  like_count  ...  reply_likes_count  post_quality
0      189892290         1.0  ...                0.0           0.0
1      181008451        16.0  ...                0.0           0.0
2      141959692         1.0  ...                0.0           0.0
3     OuTopos531         1.0  ...                0.0           0.0
4       88143349         1.0  ...                0.0           0.0
...          ...         ...  ...                ...           ...
9678   191611318         0.0  ...                1.0           0.0
9679   224115455         0.0  ...                0.0           0.0
9680   220929267         0.0  ...                1.0           0.0
9681   216257139         0.0  ...                3.0           0.0
9682   197065724         0.0  ...                0.0           0.0

[9683 rows x 6 columns]


# KMeans算法







In [ ]:
from sklearn.cluster import KMeans
X=df[['like_count','post_count','reply_count','reply_likes_count','post_quality']].values.tolist()
estimator = KMeans(n_clusters=3)#构造聚类器
estimator.fit(X)#聚类
label_pred = estimator.labels_ #获取聚类标签
print(label_pred)

[0 0 0 ... 0 0 0]


* n_clusters:簇的个数，即你想聚成几类
* init: 初始簇中心的获取方法
* n_init: 获取初始簇中心的更迭次数，为了弥补初始质心的影响，算法默认会初始10个质心，实现算法，然后返回最好的结果。
* max_iter: 最大迭代次数（因为kmeans算法的实现需要迭代）
* tol: 容忍度，即kmeans运行准则收敛的条件
* precompute_distances：是否需要提前计算距离，这个参数会在空间和时间之间做权衡，如果是True 会把整个距离矩阵都放到内存中，auto 会默认在数据样本大于featurs*samples 的数量大于12e6 的时候False,False 时核心实现的方法是利用Cpython 来实现的
* verbose: 冗长模式（不太懂是啥意思，反正一般不去改默认值）
* random_state: 随机生成簇中心的状态条件。
* copy_x: 对是否修改数据的一个标记，如果True，即复制了就不会修改数据。bool 在scikit-learn 很多接口中都会有这个参数的，就是是否对输入数据继续copy 操作，以便不修改用户的输入数据。这个要理解Python 的内存机制才会比较清楚。
* n_jobs: 并行设置
* algorithm: kmeans的实现算法，有：’auto’, ‘full’, ‘elkan’, 其中 ‘full’表示用EM方式实现

当类别为3时，结果并不是很好

In [ ]:
df['label']=label_pred
df['label'].value_counts()

0    9619
2      60
1       4
Name: label, dtype: int64

In [ ]:
estimator=KMeans(n_clusters=4)
estimator.fit(X)
label_pred=estimator.labels_
df['label']=label_pred
df['label'].value_counts()

0    9609
3      68
2       4
1       2
Name: label, dtype: int64

In [ ]:
estimator=KMeans(n_clusters=5)
estimator.fit(X)
label_pred=estimator.labels_
df['label']=label_pred
df['label'].value_counts()

0    9562
4     104
2      13
3       2
1       2
Name: label, dtype: int64

In [ ]:
estimator=KMeans(n_clusters=6)
estimator.fit(X)
label_pred=estimator.labels_
df['label']=label_pred
df['label'].value_counts()

0    9470
3     159
5      26
1      24
4       2
2       2
Name: label, dtype: int64

# SOM聚类

In [ ]:
%matplotlib inline
from numpy import *
import matplotlib.pyplot as plt
import string

class Kohonen(object):
    def __init__(self):
        self.lratemax=0.8   #最大学习率-欧式距离
        self.lratemin=0.05  #最小学习率-欧式距离
        self.rmax=5         #最大聚类半径--根据数据集
        self.rmin=0.5       #最小聚类半径--根据数据集
        self.Steps=1000     #迭代次数
        self.lratelist=[]   #学习率收敛曲线
        self.rlist=[]       #学习率半径曲线
        self.w=[]           #权重向量组
        self.M=2            # M*N表示聚类总数
        self.N=2            #M、N表示邻域的参数
        self.dataMat=[]     #外部导入数据集
        self.classLabel=[]  #聚类后的类别标签

    def loadDate(self,fileName):  #加载数据文件
    
        #fr=open(fileName)
        #for line in fr.readlines():
        #    curLine=line.strip().split("\t")
        #    lineArr=[]
        #    lineArr.append(float(curLine[0]))
        #    lineArr.append(float(curLine[1]))
        #    self.dataMat.append(lineArr)
        self.dataMat=mat(self.dataMat)
    
        self.dataMat=X

    def file2matrix(self,path, delimiter):
        recordlist = []
        fp = open(path)
        content = fp.read()
        fp.close()
        rowlist = content.splitlines()  # 按行转换为一维表
        # 逐行遍历      # 结果按分隔符分割为行向量
        recordlist = [map(eval, row.split(delimiter)) for row in rowlist if row.strip()]
        # 返回转换后的矩阵形式
        self.dataMat = mat(recordlist)

    def normalize(self,dataMat):
        [m,n]=shape(dataMat)
        for i in range(n):
           dataMat[:,i] =(dataMat[:,i]-mean(dataMat[:,]))/std(dataMat[:,])
        return dataMat

    def distEclud(self,matA,matB):
        ma, na = shape(matA);
        mb, nb = shape(matB);
        rtnmat = zeros((ma, nb))
        for i in xrange(ma):
            for j in xrange(nb):
                rtnmat[i, j] = linalg.norm(matA[i, :] - matB[:, j].T)
        return rtnmat

    def init_grid(self): #初始化第二层网格
        [m, n] = shape(self.dataMat)
        k=0 #构建低二层网络模型
        #数据集的维度即网格的维度，分类的个数即网格的行数
        grid=mat(zeros((self.M*self.N,n)))
        for i in range(self.M):
            for j in range(self.N):
                grid[k:]=[i,j]
                k+=1
        return grid
        
    def ratecalc(self,i):
        lrate = self.lratemax - (i + 1.0) * (self.lratemax - self.lratemin) / self.Steps
        r = self.rmax - ((i + 1.0) * (self.rmax - self.rmin)) / self.Steps
        return lrate,r

    #主程序
    def train(self):
        #1.构建输入层网络
        dm,dn=shape(self.dataMat)
        #归一化数据
        #normDataSet=self.normalize(self.dataMat)
        #2.初始化第二层分类网络
        grid=self.init_grid()
        #3.随机初始化两层之间的权重向量
        self.w=random.rand(dn,self.M*self.N)
        distM=self.distEclud  #确定距离公式
        #4.迭代求解
        if self.Steps<5*dm:self.Steps=5*dm  #设定最小迭代次数
        for i in xrange(self.Steps):
            lrate,r=self.ratecalc(i) #1.计算当前迭代次数下的学习率和学习聚类半径
            self.lratelist.append(lrate);self.rlist.append(r)
            #2.随机生成样本索引，并抽取一个样本
            k=random.randint(0,dm)
            mySample=self.dataMat[k,:]
            #3.计算最优节点：返回最小距离的索引值
            minIndx=(distM(mySample,self.w)).argmin()
            #4.计算领域
            d1=ceil(minIndx/self.M)  #计算此节点在第二层矩阵中的位置
            d2=mod(minIndx,self.M)
            distMat=distM(mat([d1,d2]),grid.T)
            nodelindx=(distMat<r).nonzero()[1] #获取领域内的所有点
            for j in xrange(shape(self.w)[1]):
                if sum(nodelindx==j):
                    self.w[:,j]=self.w[:,j]+lrate*(mySample[0]-self.w[:,j])
        #主循环结束

        self.classLabel=range(dm) #分配和存储聚类后的类别标签
        for i in xrange(dm):
            self.classLabel[i]=distM(normDataSet[i,:],self.w).argmin()
        self.classLabel=mat(self.classLabel)

    def showCluster(self,plt): #绘图
        lst=unique(self.classLabel.tolist()[0]) #去重
        i=0
        for cindx in lst:
            myclass = nonzero(self.classLabel==cindx)[1]
            xx=self.dataMat[myclass].copy()
            if i==0: plt.plot(xx[:,0],xx[:,1],'bo')
            elif i==1:plt.plot(xx[:,0],xx[:,1],'rd')
            elif i==2:plt.plot(xx[:,0],xx[:,1],'gD')
            elif i==3:plt.plot(xx[:,0],xx[:,1],'c^')
            i+=1
        plt.show()

if __name__=="__main__":

    SOMNet=Kohonen()
    SOMNet.loadDate('dataset2.txt')
    SOMNet.train()
    SOMNet.showCluster(plt)



ValueError: ignored

In [ ]:
import numpy as np
a = np.random.randint(50,size= (4,5))
print(a)
print(a.argmax(axis=1))

[[ 1 39 11 19 14]
 [16 43  2 47  3]
 [38 23 16 41 26]
 [29 14 41 49 39]]
[1 3 3 3]
